### PR TITLE
Add Numba / Numpy / CuPy implementations

### PR DESCRIPTION
**Pull request by houkensjtu**
Added several implementations in Numba / Numpy / CuPy. I'm still having trouble understanding some of the results. Highlights below:
1. Numba on CPU showed rather high bandwidth result (>150GB/s) for small-scale problems (<64MB). 
2. Numpy on CPU showed a flat bandwidth performance across all problem sizes.
3. Numba + CUDA showed a even worse performance than Numpy; maybe due to poor-tuned code.
4. CuPy showed an extremely high bandwidth performance (> 20,000GB/s at 256 MB problem size). 

I can explain the implementations in more details in a online-meeting. @turbo0628 @GaleSeLee Thx!

### CODE REVIEW

**Comment by GaleSeLee** [comment]
Thanks! Could you update README and offer some infos(or a fig) about performance?

**Comment by houkensjtu** [comment]
On my i9-11900K + 3080 desktop, the bandwidth results were :

cuda: [14.78, 200.42, 533.76, 612.96] GB/s
cub: [15.43, 210.52, 598.88, 689.9] GB/s
thrust: [9.18, 44.85, 369.7, 582.8] GB/s
taichi: [21.67, 175.32, 603.32, 678.88] GB/s
numba: [58.03, 229.14, 48.07, 45.93] GB/s.   # CPU
numpy: [11.87, 27.69, 23.73, 23.62] GB/s. # CPU
cupy: [17.37, 531.07, 8598.41, 34350.5] GB/s # GPU
numba_cuda: [0.39, 3.15, 5.5, 5.83] GB/s # GPU

Notice Numba and Numpy results were from CPU backend. It's just for comparison purposes to use the same bandwidth calculation. (@turbo0628 mentioned to me that it doesn't make sense to use bandwidth for CPU backends)

**Comment by GaleSeLee** [comment]
The performance of `copy` looks a bit strange. Is the reason `cupy` has cached the results in advance?

**Comment by houkensjtu** [comment]
I updated the CuPy implementation and the results look reasonable now. The problem before was that I used ```time.perf_counter()``` to measure the time spent, which was a wrong approach because GPU runtime should not be measured by a CPU time counter. The updated version use CuPy's built-in profiler @GaleSeLee . 
Please see the sample result from my desktop (You need to setup a environment variable to use the CUB backend for CuPy, See [here](https://docs.cupy.dev/en/stable/user_guide/performance.html#use-cub-cutensor-backends-for-reduction-and-other-routines)):
compute_bench_3080

**Review by GaleSeLee — APPROVED** [review]
LGTM~

**Pull request merged**
